require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - Guardfile
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - node_modules/**/*
    - test/test_helper.rb
    - vendor/**/*
    - db/data_schema.rb
  ExtraDetails: true
  NewCops: enable

Layout/AccessModifierIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - app/models/concerns/**/*

Lint/OrAssignmentToConstant:
  Enabled: false

Lint/UnusedMethodArgument:
  Exclude:
    - app/models/forecast.rb

Lint/Void:
  Exclude:
    - lib/tasks/surfline.rake

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Performance/Size:
  Enabled: true

Rails/InverseOf:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/NumericLiterals:
  Exclude:
    - db/seeds.rb

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
